### ISSUE TITLE
Argo workflows, events and rollouts

### ISSUE THREAD

**Issue by sidkris77** [argoproj-labs/argocd-autopilot#201]
Can you use auto pilot in combination with Argo workflows, events and rollouts? Basically automate the entire CI/CD. I did see a mention of workflows under the Application Specifier section in the docs. Thanks.

**Comment by myspotontheweb** [comment]
As long as Argo Workflows is installed on the target cluster, there should be no reason why you can't submit a normal Workflow CRD using Kustomize.

Take this example repo

* https://github.com/myspotontheweb/gitops-workloads

The YAML that is generated by Kustomize can be inspected as follows. It is fairly trivial to generate other YAML objects. 

````
kubectl apply -oyaml -k apps/gitops-demo-app1/overlays/dev
````

To conclude, no mention is made in the docs about Argo Workflows, because ArgoCD is capable supporting any valid Kubernetes CRD.

**Comment by todaywasawesome** [comment]
@sidkris77 To combine Workflows, events, rollouts, and CD to automate the entire CI/CD I suggest trying [Codefresh Software Delivery Platform](https://codefresh.io/product/). It does what you're asking.
