### ISSUE TITLE
Pretty-format JSON configs in app directory

### ISSUE THREAD

**Issue by vadimgusev-codefresh** [argoproj-labs/argocd-autopilot#232]
Currently `config_dir.json`s are created as single line files. They can be pretty-formatted manually for better readability and maintenance after bootstrapping, but having them that way from the beginning would be a nice enhancement.

**Comment by krishnaduttPanchagnula** [comment]
hi @vadimgusev-codefresh has this been taken up ? or shall i take it?

**Comment by noam-codefresh** [comment]
@vadimgusev-codefresh @krishnaduttPanchagnula 

the `config.json` and `config_dir.json` files created when adding new applications are already formatted correctly since [v0.3.2](https://github.com/argoproj-labs/argocd-autopilot/releases/tag/v0.3.2)

the only json file that is being written without indentation is the cluster config file, and it just contains two fields, so i think that's not too bad:
```json
{"name":"in-cluster","server":"https://kubernetes.default.svc"}
```
