### ISSUE TITLE
Cannot use `master` as branch

### ISSUE THREAD

**Issue by NPastorale** [argoproj-labs/argocd-autopilot#340]
## Expected behaviour
When either having `master` as the default branch or specifying it with the `?ref=master` notation when running `repo bootstrap` it should use that branch to commit the bootstrapping files

## Actual behaviour
Regardless of how I try to execute it, having tried (I think) all the possible combinations of having the branch defined in `.gitconfig`, using it as `?ref=master`, toying with the default branch name in GitHub, with and without the `-b` flag, I have been unable to get to a different result other than `FATAL failed to initialize repository: a branch named "refs/heads/master" already exists`

## Additional comments
 - This may very well be a duplicate of #198 but I still wanated to create a new issue as I think it not as a readme issue, but as a failure of now available flags
 - I have also noticed that a `main` branch is always created regardless of the default defined either in GitHub or in `.gitconfig`
 - Is there any way to bootstrap to master?

**Comment by roi-codefresh** [comment]
Before: https://github.com/argoproj-labs/argocd-autopilot/pull/333, we used to always prefer `main` because we did not check the provider for the default branch.

Because of the way we did stuff before this PR, you actually ended up with a repository with both `main` and `master` (empty branch). So this is the reason you see this: 
```
FATAL failed to initialize repository: a branch named "refs/heads/master" already exists
```

However, if you create another repo with the latest autopilot version you should have only a single branch and it should hopefully be the default branch based on your github account settings.

Closing this issue now, let me know if it doesn't work for you yet.

**Comment by NPastorale** [comment]
I can confirm it is now working as I initially expected. Just for the sake of completion, this is what I'm running
```
docker run --rm -v ~/.kube:/home/autopilot/.kube -v ~/.gitconfig:/home/autopilot/.gitconfig -it quay.io/argoprojlabs/argocd-autopilot:v0.4.2 repo bootstrap --repo REPO --git-token TOKEN
```
Without specifying the `?ref=master`

Thanks!
