### ISSUE TITLE
Packr management issues

### ISSUE THREAD

**Issue by sestegra** [argoproj-labs/argocd-autopilot#76]
After investigating issue on #31, I found the following recommandation about `packr`.
```
Please consider migrating your projects to github.com/markbates/pkger
```

Then, `static` option should be removed from `hack/build.sh` to support macOS on arm64 architecture: see https://github.com/Homebrew/homebrew-core/pull/78460.

**Comment by roi-codefresh** [comment]
We actually only use packr because we have a dependency on argo-cd which is using packr to embed some static files in their binary. 

I think there are two possible ways to resolve it (besides upgrading to `github.com/markbates/pkger`):
1. we can make a pr to argo-cd and replace the use of packr to the built-in `embed` go module.
2. If I understand correctly what packr is doing is just generating `*.go` files that contain the data to be embedded, then they compile the source code with those files and finally they clean the generated files. We could potentially just keep the generated file (commit it) and compile with it, then we can stop using packr.

**Comment by roi-codefresh** [comment]
Argo-cd actually just removed the dependency on packr two weeks ago with [this commit](https://github.com/argoproj/argo-cd/commit/3f32a750a014ba818301b3e99e94be619eb18b1f). However it is not yet present on the latest release, which is `v2.0.3`. For the meantime I have implemented some hack to remove our dependency on packr, but if we upgrade to a newer version of argo-cd this hack would no longer work and hopefully there would be no issues making it work with go-embbed.
